# Generated by Django 4.1 on 2022-09-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_picture'),
        ('blog', '0005_comment_author_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike',
            field=models.ManyToManyField(related_name='post_dislike', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(related_name='post_like', to='accounts.userprofile'),
        ),
    ]
